# Generated by Django 4.2.1 on 2025-02-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shouhin',
            fields=[
                ('hontai_num', models.AutoField(primary_key=True, serialize=False, verbose_name='本体No')),
                ('shouhin_num', models.CharField(blank=True, max_length=255, null=True, verbose_name='商品番号')),
                ('shouhin_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='商品名')),
                ('color', models.CharField(blank=True, max_length=255, null=True, verbose_name='カラー')),
                ('size', models.CharField(blank=True, max_length=255, null=True, verbose_name='サイズ')),
                ('size_num', models.IntegerField(default=0, verbose_name='サイズ値')),
                ('tana', models.CharField(blank=True, max_length=255, null=True, verbose_name='棚番号')),
                ('bikou', models.CharField(blank=True, max_length=255, null=True, verbose_name='備考')),
                ('joutai', models.IntegerField(default=0, verbose_name='状態')),
                ('rental_day', models.CharField(blank=True, max_length=255, null=True, verbose_name='貸出日')),
                ('rental_tantou', models.CharField(blank=True, max_length=255, null=True, verbose_name='担当')),
                ('rental_cus', models.CharField(blank=True, max_length=255, null=True, verbose_name='顧客')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_num', models.IntegerField(verbose_name='順番')),
                ('size', models.CharField(blank=True, max_length=255, verbose_name='サイズ')),
            ],
        ),
    ]
