# Generated by Django 4.2.1 on 2025-02-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shouhin',
            name='team',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='拠点'),
        ),
    ]
